<?php
    $helper = $this->helper('Dev\UserAccountField\Helper\Frontend\Options');
    $configArray = $helper->getConfig();   
?>
<div class="field select_field required">
   <label class="label" for="select_field">
       <span><?= $block->escapeHtml(__('Select Field')) ?></span>
   </label>
   <div class="control">
        <select id="select_field" name="select_field">
            <option value="">Please Select Value</option>
            <?php 
                foreach ($configArray as $key => $value) {
            ?> 
            <option value="<?php echo $key;?>"><?php echo $value;?></option>
            <?php
                }
            ?>
        </select>
   </div>
</div>